name: Build and Deploy Documentation
on:
  release:
    types:
    - published
  workflow_dispatch: null
jobs:
  docs:
    uses: Billingegroup/release-scripts/.github/workflows/_docs.yml@main
    with:
      project: diffpy.utils
      c_extension: false
