name: Test
on:
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
jobs:
  validate:
    uses: Billingegroup/release-scripts/.github/workflows/_main.yml@main
    with:
      project: diffpy.utils
      c_extension: false
      headless: false
