name: Deploy Documentation on Release

on:
  release:
    types: [published, prereleased]
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    uses: Billingegroup/release-scripts/.github/workflows/_publish-docs-on-release.yml@v0
    with:
      project: diffpy.utils
      c_extension: false
      headless: false
